version: '3.9'

services:
  flask:
    container_name: flask
    image: flask:latest
    build: .
    ports:
      - "80:80"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    networks:
      - backend

  postgres:
    environment:
      DATABASE_PORT: 5432
      DATABASE_DIALECT: postgresql
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres_flask_container
    image: postgres:16
    volumes:
      - flaskdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - backend

  pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: server@myapp.de
        PGADMIN_DEFAULT_PASSWORD: XXXX
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
        - pgadmin:/var/lib/pgadmin
      ports:
        - "${PGADMIN_PORT:-5050}:80"
      restart: unless-stopped
      networks:
        - backend

volumes:
  flaskdb:

  pgadmin:
    driver: local

networks:
  backend:
    driver: bridge

